Update install

diff --git a/gestorssh/install b/gestorssh/install
--- a/gestorssh/install
+++ b/gestorssh/install
@@ -9,7 +9,7 @@ apt install figlet boxes -y &>/dev/null
 echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
 rm $HOME/Plus > /dev/null 2>&1; exit 0
 }
-_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
+#_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 cd $HOME
 fun_bar () {
 comando[0]="$1"
@@ -37,15 +37,15 @@ done
 echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
 tput cnorm
 }
-function verif_key () {
-krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
-[[ ! -e "$_Ink/list" ]] && {
-echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
-rm -rf $HOME/Plus > /dev/null 2>&1
-sleep 2
-clear; exit 1
-}
-}
+#function verif_key () {
+#krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
+#[[ ! -e "$_Ink/list" ]] && {
+#echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+#rm -rf $HOME/Plus > /dev/null 2>&1
+#sleep 2
+#clear; exit 1
+#}
+#}
 system=$(cat /etc/issue.net)
 date=$(date '+%Y-%m-%d <> %H:%M:%S')
 echo ""
@@ -65,18 +65,18 @@ echo -e "\033[1;37m \033[1;37m\033[0m"
 echo ""
 echo -e "\033[1;32m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
 echo ""
-echo -ne "\033[1;32mINFORME SUA KEY:\033[1;32m "; read _key_
-if [[ -z $_key_ ]]; then
-echo ""
-echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
-sleep 1
-clear; exit
-fi
-sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
-service ssh restart  > /dev/null 2>&1
-echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $_key_\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink http://51.222.100.29/$_key_/list > /dev/null 2>&1; verif_key
-sleep 3s
-echo -e "\033[1;31m KEY VALIDA\033[1;32m"
+#echo -ne "\033[1;32mINFORME SUA KEY:\033[1;32m "; read _key_
+*if [[ -z $_key_ ]]; then
+#echo ""
+#echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
+#sleep 1
+#clear; exit
+#fi
+#sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+#service ssh restart  > /dev/null 2>&1
+*echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $_key_\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink http://51.222.100.29/$_key_/list > /dev/null 2>&1; verif_key
+#sleep 3s
+#echo -e "\033[1;31m KEY VALIDA\033[1;32m"
 sleep 3s
 function inst_base {
 apt-get update > /dev/null 2>&1
